[package]
name = "taoirc"
version = "0.1.0"
authors = ["Kim Nilsson <kim@wayoftao.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop-util = { version = "^0.19.6", features = ["lexer"] }
